//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OlympicsStatistics.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Partecipation
    {
        public int Id { get; set; }
        public int IdAthlete { get; set; }
        public Nullable<short> Age { get; set; }
        public string NOC { get; set; }
        public int IdGame { get; set; }
        public string City { get; set; }
        public int IdEvent { get; set; }
    
        public virtual AthletesNF AthletesNF { get; set; }
        public virtual Event Event { get; set; }
        public virtual Game Game { get; set; }
    }
}
